[package]
name = "themelio-core"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

[workspace] 

[dependencies]
autosmt={path="libs/autosmt"}
blkstructs={path="libs/blkstructs"}
tmelcrypt={path="libs/tmelcrypt"}
melpow={path="libs/melpow"}
symphonia={path="libs/symphonia"}
neosymph={path="libs/neosymph"} 
melnet={path="libs/melnet"} 
hex= "0.4.2"
smol= "1.2.3"
colored= "2.0.0"
anyhow= "1.0.32"
tabwriter= "1.2.1"
env_logger= "0.7.1"
rustyline= "6.3.0"
log= "0.4.11"
attohttpc={ version = "0.15.0", default-features = false, features = [] }
clap= "2.33.3"
parking_lot= "0.11.0"
rand= "0.7.3"
lru= "0.6.0"
scopeguard= "1.1.0"
lmdb= "0.8.0"
derive_more= "0.99.11"
defmac= "0.2.1"
structopt= "0.3.18"
serde = {version="1.0.116", features=["derive"]}
bincode = "1.3.1"
im = { version = "15.0.0", features = ["serde"] }
rusqlite = "0.24.0"
smolscale="0.1.2"

tracing = { version = "0.1.22", features=["log"] }
tracing-log = "0.1.1"
tracing-futures="0.2"
tracing-subscriber = "0.2"



[profile.dev]
panic = "abort"
opt-level = 0

[profile.release]
panic = "abort"
opt-level = 3
lto = "thin"