[package]
name = "themelio-core"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

[workspace] 

[dependencies]
autosmt={path="libs/autosmt"}
blkstructs={path="libs/blkstructs"}
tmelcrypt={path="libs/tmelcrypt"}
melpow={path="libs/melpow"}
hex="0.4.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"