[package]
name = "themelio-core"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

[workspace] 

[dependencies]
autosmt={path="libs/autosmt"}
blkstructs={path="libs/blkstructs"}
tmelcrypt={path="libs/tmelcrypt"}
melpow={path="libs/melpow"}
symphonia={path="libs/symphonia"}
melnet={path="libs/melnet"}
hex="0.4.2"
futures="0.3"
smol="0.1"
anyhow="1"
smol-potat="0.3"
env_logger="0.7"
log="0.4"
attohttpc={version = "0.15", default-features = false, features=[]}
clap="2"
parking_lot="0.11"
rand="0.7"
lru="0.5"
scopeguard="1.1"
lmdb="0.8"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 'z'
#lto = true