[package]
name = "themelio-core"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

[workspace] 

[dependencies]
test_crate={path="libs/test_crate"}
smart_smt={path="libs/smart_smt"}
hex="0.4.2"